# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meterusage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='meterusage.proto',
  package='meterusage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10meterusage.proto\x12\nmeterusage\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n\x11MeterUsageRequest\"R\n\x12MeterUsageResponse\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nmeterusage\x18\x02 \x01(\x01\x32g\n\x11MeterUsageService\x12R\n\rGetMeterUsage\x12\x1d.meterusage.MeterUsageRequest\x1a\x1e.meterusage.MeterUsageResponse\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_METERUSAGEREQUEST = _descriptor.Descriptor(
  name='MeterUsageRequest',
  full_name='meterusage.MeterUsageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=84,
)


_METERUSAGERESPONSE = _descriptor.Descriptor(
  name='MeterUsageResponse',
  full_name='meterusage.MeterUsageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='meterusage.MeterUsageResponse.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meterusage', full_name='meterusage.MeterUsageResponse.meterusage', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=168,
)

_METERUSAGERESPONSE.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['MeterUsageRequest'] = _METERUSAGEREQUEST
DESCRIPTOR.message_types_by_name['MeterUsageResponse'] = _METERUSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MeterUsageRequest = _reflection.GeneratedProtocolMessageType('MeterUsageRequest', (_message.Message,), {
  'DESCRIPTOR' : _METERUSAGEREQUEST,
  '__module__' : 'meterusage_pb2'
  # @@protoc_insertion_point(class_scope:meterusage.MeterUsageRequest)
  })
_sym_db.RegisterMessage(MeterUsageRequest)

MeterUsageResponse = _reflection.GeneratedProtocolMessageType('MeterUsageResponse', (_message.Message,), {
  'DESCRIPTOR' : _METERUSAGERESPONSE,
  '__module__' : 'meterusage_pb2'
  # @@protoc_insertion_point(class_scope:meterusage.MeterUsageResponse)
  })
_sym_db.RegisterMessage(MeterUsageResponse)



_METERUSAGESERVICE = _descriptor.ServiceDescriptor(
  name='MeterUsageService',
  full_name='meterusage.MeterUsageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=170,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMeterUsage',
    full_name='meterusage.MeterUsageService.GetMeterUsage',
    index=0,
    containing_service=None,
    input_type=_METERUSAGEREQUEST,
    output_type=_METERUSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METERUSAGESERVICE)

DESCRIPTOR.services_by_name['MeterUsageService'] = _METERUSAGESERVICE

# @@protoc_insertion_point(module_scope)
